name: easyride
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0' # Broaden SDK range for better compatibility
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0 # Updated to latest stable as of June 2025
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.19.0 # Updated to latest stable as of June 2025
  cloud_firestore: ^4.17.0 # Updated to latest stable as of June 2025
  # js: ^0.6.7 # Removed: This is usually handled by Firebase plugins implicitly

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/im1.png
    - assets/images/im2.png
    - assets/images/im3.png
    - assets/images/s1.jpeg